on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Lanzamiento
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obtener los archivos.
      uses: actions/checkout@v3
    
    - name: 📂 Sincronizar archivos.
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/
